name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  injectable: ^2.5.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  mockito: ^5.4.6
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
