// Mocks generated by Mockito 5.4.6 from annotations
// in todo_app/test/feature/todo/repository/mock_todo_local_source.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/feature/todo/model/todo_model.dart' as _i4;

import 'mock_todo_local_source.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TodoLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoLocalSource extends _i1.Mock implements _i2.TodoLocalSource {
  MockTodoLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TodoModel>> fetch() =>
      (super.noSuchMethod(
            Invocation.method(#fetch, []),
            returnValue: _i3.Future<List<_i4.TodoModel>>.value(
              <_i4.TodoModel>[],
            ),
          )
          as _i3.Future<List<_i4.TodoModel>>);

  @override
  _i3.Future<bool> add(_i4.TodoModel? todo) =>
      (super.noSuchMethod(
            Invocation.method(#add, [todo]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
