// Mocks generated by Mockito 5.4.6 from annotations
// in todo_app/test/feature/theme/view_model/theme_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/core/failure.dart' as _i5;
import 'package:todo_app/feature/theme/model/theme_model.dart' as _i6;
import 'package:todo_app/feature/theme/repository/theme_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ThemeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeRepository extends _i1.Mock implements _i3.ThemeRepository {
  MockThemeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ThemeModel>> getTheme() =>
      (super.noSuchMethod(
            Invocation.method(#getTheme, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ThemeModel>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ThemeModel>(
                    this,
                    Invocation.method(#getTheme, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ThemeModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> setTheme(
    _i6.ThemeModel? theme,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setTheme, [theme]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#setTheme, [theme]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
